Fix Default Workdir for Unweave Code/SSH + ExecInfo UX
unweave/cli pull request #14
Opened 2023-05-30 14:37 UTC by mmacheerpuppy

This PR cleans up some unused code in the CLI, makes UX improvements based on https://github.com/unweave/unweave/pull/13, and fixes a bug where the workdir used for Node and SSH was inconsistent.

![image](https://github.com/unweave/cli/assets/8885269/8697b4bd-3bd2-4054-b171-84c957ba31dd)

2023-05-30 16:58 UTC, mmacheerpuppy commented on session/session.go
> +		// {Key: "RAM", Value: fmt.Sprintf("%vGB", exec.Specs.RAM.Min)},
uncomment this line when ready

2023-05-31 08:25 UTC, noorvir requested changes

2023-05-31 08:25 UTC, noorvir commented on cmd/exec.go
> -}
Do we not use this anymore? I'm not sure this should be removed since we want to implement getting info about an exec soon.

2023-05-31 08:25 UTC, noorvir commented on config/dirpath.go
> +}
This is not correct. The user can be executing an unweave command from a subdirectory too. We have a utility to get the project linked directory [here](https://github.com/unweave/cli/blob/master/config/config.go#L63)

2023-05-31 21:27 UTC, mmacheerpuppy commented on cmd/exec.go
> -}
No references anywhere, will keep it in if you want but I'm an evangelicalist about removing dead code and dead features

2023-06-01 12:39 UTC, noorvir commented on cmd/exec.go
> -}
We'll probably implement this very soon so let's leave it.

2023-06-01 14:38 UTC, noorvir approved these changes

2023-06-01 14:38 UTC, merged