store download directory and store list path
unweave/cli pull request #28
Opened 2022-08-29 03:28 UTC by markwinter

This makes two changes:

- `store list` now takes an optional path to list a certain directory in the store
- `store download <path>` now can take a directory path and it will download everything in the directory

```
$ ~/Code/cli/unweave store download data/MNIST
Downloading "t10k-images-idx3-ubyte" to ./uwstore/data/MNIST/raw/t10k-images-idx3-ubyte Downloaded!
Downloading "t10k-labels-idx1-ubyte" to ./uwstore/data/MNIST/raw/t10k-labels-idx1-ubyte Downloaded!
Downloading "train-images-idx3-ubyte" to ./uwstore/data/MNIST/raw/train-images-idx3-ubyte Downloaded!
Downloading "train-labels-idx1-ubyte" to ./uwstore/data/MNIST/raw/train-labels-idx1-ubyte Downloaded!
```

```
$ ~/Code/cli/unweave store list data/MNIST/
2022-08-26 22:05:38 +0900 KST	7.8 MB	data/MNIST/raw/t10k-images-idx3-ubyte
2022-08-26 22:05:39 +0900 KST	10 kB	data/MNIST/raw/t10k-labels-idx1-ubyte
2022-08-26 11:15:03 +0900 KST	47 MB	data/MNIST/raw/train-images-idx3-ubyte
2022-08-26 11:15:08 +0900 KST	60 kB	data/MNIST/raw/train-labels-idx1-ubyte
```

2022-08-29 03:29 UTC, markwinter commented on controller/store.go
> +		if object.Path == "" {
Thinking about adding this to the workbench instead

2022-08-29 04:27 UTC, markwinter commented on controller/store.go
> +		if object.Path == "" {
Will require a breaking change to how listing in dashboard so will be done later.

2022-08-29 04:49 UTC, noorvir commented
Is this implemented on the `api` and `workbench` side?

2022-08-29 04:51 UTC, markwinter commented
Yes that's what was just merged https://github.com/unweave/unweave/pull/459

2022-08-29 05:05 UTC, noorvir requested changes

2022-08-29 06:10 UTC, markwinter commented on controller/store.go
> +	for _, err := range errs {
We print after because any printing during would mess up the other download bars

2022-08-31 03:40 UTC, markwinter commented
Was very simple to add an `store ls` alias for `store list` with cobra. Added based on that user's feedback.

2022-08-31 03:44 UTC, noorvir commented on main.go
> +		Use:     "list [path]",
Let's invert this though. Let's add the main command to be `ls` and the alias to be `list`. This should also be done in the root `list` command

2022-08-31 04:02 UTC, markwinter commented on main.go
> +		Use:     "list [path]",
Done 👍

2022-08-31 04:57 UTC, noorvir approved these changes

2022-08-31 04:57 UTC, merged